version: "3.6"
services: 
    web: 
        build: .
        container_name: flask
        command: python -u app.py
        ports: 
            - "5000:5000"
        volumes:
            - .:/app
        depends_on: 
            - mongodb
    mongodb:
        image: mongo:latest
        restart: always
        user: '1000:1000' #to avoid permission conflicts
        container_name: mongodb
        ports: 
            - "27017:27017"
        volumes:
            - ./data:/data/db